version: "3.8"
services:
  # Database Server
  database:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver_container_curso
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_USER: root
      MSSQL_SA_PASSWORD: P@ssword123
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql
volumes:
  db-data: ~